### ISSUE TITLE
branding and html id are missing during page creation

### ISSUE THREAD

**Issue by reusr1** [adobe/aem-site-template-standard#39]
### Expected Behaviour

add a branding name and html id to a page when creating a new page

### Actual Behaviour

the branding and thml id field are not displayed during the create page process

#### Steps to Reproduce

create a new page based on the core components base page

#### Platform and Version

cloud, latest as of today

#### Sample Code that illustrates the problem

![Screenshot from 2021-04-22 09-03-41](https://user-images.githubusercontent.com/779992/115754233-d919f400-a350-11eb-86de-0e0266eaec03.png)

**Comment by gabrielwalt** [comment]
The problem seems to be a general Core Component problem, and not specific to the site template: the Core Page component dialog is configured so that the "Branding" and "HTML ID" options aren't showed in the page creation wizard.
The issue probably is a missing `cq:showOnCreate=true` property on the `brandSlug` and `htmlid` dialog definition nodes.

It is debatable however if those options should always be presented in the page creation wizard though, because they are probably very infrequently defined at page creation.

I created a Core Component issue to track and resolve that:
https://github.com/adobe/aem-core-wcm-components/issues/1971
